# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:
  - task: DotNetCoreCLI@2  
    condition: eq(variables['System.PullRequest.PullRequestId'], '')
    displayName: Install NBGV tool
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . nbgv

  - script: nbgv cloud -a -c
    condition: eq(variables['System.PullRequest.PullRequestId'], '')
    displayName: Set build number

  # Currently Azure pipelines won't let PRs from forks setting the build ID
  # so we need to come up with a version number to use for the build
  - task: PowerShell@2
    condition: ne(variables['System.PullRequest.PullRequestId'], '')
    displayName: Set temporary build number
    inputs:
        targetType: 'inline'
        script: |
            Write-Host "$("##vso[task.setvariable variable=NBGV_Version]")0.0.0.$env:System_PullRequest_PullRequestNumber"
