version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
clone_depth: 1
install:
- ps: .\install-vsix-appveyor.ps1
build_script:
- ps: >-
    nuget restore targets\os\win32\nanoCLR.sln

    msbuild targets\os\win32\nanoCLR.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
notifications:
- provider: Slack
  auth_token:
    secure: 2tqAJTTbN2dm24Vrwo5TXun3Vxc34R5G9l7o3pK3xEuKZAzxx3nbP2yGkMI/kl3+NxHXknjBfZnkhZC5eLYBHb+jO7YVUZwPYOfC/ZGy5HU=
  channel: '#build-monitor'
  on_build_status_changed: true
  on_build_success: false
  on_build_failure: false
